
import type { InstagramPost, InstagramUserProfile } from './types';

export const demoInstagramPosts: InstagramPost[] = [
  {
    id: 'ig1',
    platform: 'instagram',
    caption: 'Exploring the beautiful mountains of Switzerland! #travel #nature #adventure',
    author: '@swiss.explorer',
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    metrics: {
      likes: 1200,
      comments: 80,
    },
    thumbnailUrl: 'https://picsum.photos/seed/ig1/480/480',
    mediaType: 'IMAGE',
  },
   {
    id: 'ig2',
    platform: 'instagram',
    caption: 'Unboxing a classic. The sound of nostalgia!',
    author: '@console.classics',
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: {
      likes: 5400,
      comments: 250,
    },
    thumbnailUrl: 'https://picsum.photos/seed/ig2/480/480',
    mediaType: 'VIDEO',
  },
  {
    id: 'ig3',
    platform: 'instagram',
    caption: 'My cozy desk setup for a productive week. #wfh #desksetup #productivity',
    author: '@codeandcoffee',
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: {
      likes: 8000,
      comments: 400,
    },
thumbnailUrl: 'https://picsum.photos/seed/ig3/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig4',
    platform: 'instagram',
    caption: 'A quick tutorial on how to make the perfect latte art. ☕️ #latteart #coffee #tutorial',
    author: '@barista.daily',
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    metrics: {
      likes: 2500,
      comments: 150,
    },
    thumbnailUrl: 'https://picsum.photos/seed/ig4/480/480',
    mediaType: 'VIDEO',
  },
];

export const demoUserProfile: InstagramUserProfile = {
  id: 'user123',
  username: 'travel.junkie',
  fullName: 'Alex Doe',
  profilePictureUrl: 'https://picsum.photos/seed/user123/150/150',
  followers: 125000,
  following: 500,
  postCount: 789,
  engagementRate: 2.5,
  avgLikes: 3125,
  avgComments: 150,
  postingFrequency: "1 post every 2 days",
  recentPosts: [
    {
      id: 'post1',
      platform: 'instagram',
      caption: 'Golden hour in Santorini. Unforgettable! Featuring my friend @photo.fiend',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post1',
      publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 4500, comments: 230 },
      thumbnailUrl: 'https://picsum.photos/seed/post1/480/480',
      mediaType: 'IMAGE',
    },
    {
      id: 'post2',
      platform: 'instagram',
      caption: 'Exploring the vibrant streets of Tokyo with @tokyo.explorer.',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post2',
      publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 3800, comments: 190 },
      thumbnailUrl: 'https://picsum.photos/seed/post2/480/480',
      mediaType: 'IMAGE',
    },
    {
      id: 'post3',
      platform: 'instagram',
      caption: 'A quick reel of my trip to the Amazon! Big thanks to @rainforest.guides for the tour.',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post3',
      publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 6200, comments: 450 },
      thumbnailUrl: 'https://picsum.photos/seed/post3/480/480',
      mediaType: 'VIDEO',
    },
    {
      id: 'post4',
      platform: 'instagram',
      caption: 'What to pack for a weekend getaway. #traveltips Thanks @everyday.carry for the gear!',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post4',
      publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 2900, comments: 120 },
      thumbnailUrl: 'https://picsum.photos/seed/post4/480/480',
      mediaType: 'CAROUSEL_ALBUM',
    },
     {
      id: 'post5',
      platform: 'instagram',
      caption: 'Lost in the grand bazaar of Istanbul. @photo.fiend took this shot!',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post5',
      publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 4100, comments: 210 },
      thumbnailUrl: 'https://picsum.photos/seed/post5/480/480',
      mediaType: 'IMAGE',
    },
     {
      id: 'post6',
      platform: 'instagram',
      caption: 'Sunrise over the Sahara desert. An amazing experience organized by @desert.adventures.',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post6',
      publishedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 5300, comments: 300 },
      thumbnailUrl: 'https://picsum.photos/seed/post6/480/480',
      mediaType: 'IMAGE',
    }
  ],
  followerHistory: [
    { date: 'Jan', value: 110000 },
    { date: 'Feb', value: 112000 },
    { date: 'Mar', value: 115000 },
    { date: 'Apr', value: 118000 },
    { date: 'May', value: 122000 },
    { date: 'Jun', value: 125000 },
  ],
  engagementHistory: [
    { date: 'Jan', value: 2.8 },
    { date: 'Feb', value: 2.6 },
    { date: 'Mar', value: 2.9 },
    { date: 'Apr', value: 2.7 },
    { date: 'May', value: 2.4 },
    { date: 'Jun', value: 2.5 },
  ],
  topMentions: [], // Will be populated by the flow
};
