
import type { InstagramPost, InstagramUserProfile } from './types';

export const demoInstagramPosts: InstagramPost[] = [
  {
    id: 'ig1',
    platform: 'instagram',
    caption: 'Exploring the beautiful mountains of Switzerland! #travel #nature #adventure. An amazing trip!',
    author: '@swiss.explorer',
    authorFollowers: 25000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 1800, comments: 120 },
    thumbnailUrl: 'https://picsum.photos/seed/ig1/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig2',
    platform: 'instagram',
    caption: 'Unboxing a classic. The sound of nostalgia! #gaming #retrogaming',
    author: '@console.classics',
    authorFollowers: 150000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 5400, comments: 250 },
    thumbnailUrl: 'https://picsum.photos/seed/ig2/480/480',
    mediaType: 'VIDEO',
  },
  {
    id: 'ig3',
    platform: 'instagram',
    caption: 'My cozy desk setup for a productive week. #wfh #desksetup #productivity',
    author: '@codeandcoffee',
    authorFollowers: 80000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 8000, comments: 400 },
    thumbnailUrl: 'https://picsum.photos/seed/ig3/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig4',
    platform: 'instagram',
    caption: 'A quick tutorial on how to make the perfect latte art. ☕️ #latteart #coffee #tutorial',
    author: '@barista.daily',
    authorFollowers: 50000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 2500, comments: 150 },
    thumbnailUrl: 'https://picsum.photos/seed/ig4/480/480',
    mediaType: 'VIDEO',
  },
  {
    id: 'ig5',
    platform: 'instagram',
    caption: 'Our new puppy is settling in! Look at that face. #dogsofinstagram #puppylove',
    author: '@doglife',
    authorFollowers: 120000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 15000, comments: 800 },
    thumbnailUrl: 'https://picsum.photos/seed/ig5/480/480',
    mediaType: 'CAROUSEL_ALBUM',
  },
  {
    id: 'ig6',
    platform: 'instagram',
    caption: 'Just finished a 10k run! Feeling great. #running #fitness #motivation',
    author: '@run.fast',
    authorFollowers: 30000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 2200, comments: 180 },
    thumbnailUrl: 'https://picsum.photos/seed/ig6/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig7',
    platform: 'instagram',
    caption: 'Baking sourdough bread from scratch. The smell is incredible! #baking #sourdough #homemade',
    author: '@baking.love',
    authorFollowers: 65000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 4200, comments: 300 },
    thumbnailUrl: 'https://picsum.photos/seed/ig7/480/480',
    mediaType: 'VIDEO',
  },
  {
    id: 'ig8',
    platform: 'instagram',
    caption: 'A weekend trip to the coast. #beach #ocean #weekendgetaway',
    author: '@weekend.vibes',
    authorFollowers: 15000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 1100, comments: 70 },
    thumbnailUrl: 'https://picsum.photos/seed/ig8/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig9',
    platform: 'instagram',
    caption: 'My top 5 favorite books of the year. #bookstagram #reading #books',
    author: '@bookworm.life',
    authorFollowers: 95000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 6800, comments: 550 },
    thumbnailUrl: 'https://picsum.photos/seed/ig9/480/480',
    mediaType: 'CAROUSEL_ALBUM',
  },
  {
    id: 'ig10',
    platform: 'instagram',
    caption: 'Learning to play the guitar. It’s harder than it looks! #guitar #music #newhobby',
    author: '@music.man',
    authorFollowers: 20000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 1500, comments: 200 },
    thumbnailUrl: 'https://picsum.photos/seed/ig10/480/480',
    mediaType: 'VIDEO',
  },
  {
    id: 'ig11',
    platform: 'instagram',
    caption: 'Street art in Berlin. So much talent in this city. #streetart #berlin #art',
    author: '@art.hunter',
    authorFollowers: 45000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 3500, comments: 220 },
    thumbnailUrl: 'https://picsum.photos/seed/ig11/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig12',
    platform: 'instagram',
    caption: 'Trying out a new recipe for vegan pasta. Delicious! #vegan #recipe #food',
    author: '@vegan.eats',
    authorFollowers: 110000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 9500, comments: 600 },
    thumbnailUrl: 'https://picsum.photos/seed/ig12/480/480',
    mediaType: 'VIDEO',
  },
   {
    id: 'ig13',
    platform: 'instagram',
    caption: 'Morning yoga session to start the day right. #yoga #mindfulness #healthylifestyle',
    author: '@yogajourney',
    authorFollowers: 75000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 3200, comments: 180 },
    thumbnailUrl: 'https://picsum.photos/seed/ig13/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig14',
    platform: 'instagram',
    caption: 'A stunning sunset over the city skyline. #sunset #cityscape #photography',
    author: '@city.lights',
    authorFollowers: 200000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 25000, comments: 1200 },
    thumbnailUrl: 'https://picsum.photos/seed/ig14/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig15',
    platform: 'instagram',
    caption: 'My minimalist bullet journal setup for the month. #bujo #bulletjournal #organization',
    author: '@journal.with.me',
    authorFollowers: 85000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 7200, comments: 450 },
    thumbnailUrl: 'https://picsum.photos/seed/ig15/480/480',
    mediaType: 'CAROUSEL_ALBUM',
  },
   {
    id: 'ig16',
    platform: 'instagram',
    caption: 'The ultimate guide to home gardening. #gardening #plants #greenthumb',
    author: '@homegrown',
    authorFollowers: 130000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 9800, comments: 650 },
    thumbnailUrl: 'https://picsum.photos/seed/ig16/480/480',
    mediaType: 'VIDEO',
  },
  {
    id: 'ig17',
    platform: 'instagram',
    caption: 'Hiking to the top of the world. What a view! #hiking #outdoors #adventure',
    author: '@mountain.man',
    authorFollowers: 60000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 4800, comments: 320 },
    thumbnailUrl: 'https://picsum.photos/seed/ig17/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig18',
    platform: 'instagram',
    caption: 'A simple and delicious pasta recipe. #foodie #recipe #pasta',
    author: '@pastalover',
    authorFollowers: 90000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 6200, comments: 400 },
    thumbnailUrl: 'https://picsum.photos/seed/ig18/480/480',
    mediaType: 'VIDEO',
  },
  {
    id: 'ig19',
    platform: 'instagram',
    caption: 'My favorite corner in our home. #homedecor #interiordesign #cozy',
    author: '@home.sweet.home',
    authorFollowers: 180000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 18000, comments: 900 },
    thumbnailUrl: 'https://picsum.photos/seed/ig19/480/480',
    mediaType: 'IMAGE',
  },
  {
    id: 'ig20',
    platform: 'instagram',
    caption: 'The art of pottery. A relaxing and creative process. #pottery #ceramics #art',
    author: '@pottery.world',
    authorFollowers: 40000,
    url: 'https://www.instagram.com',
    publishedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    metrics: { likes: 3800, comments: 250 },
    thumbnailUrl: 'https://picsum.photos/seed/ig20/480/480',
    mediaType: 'VIDEO',
  }
];

export const demoUserProfile: InstagramUserProfile = {
  id: 'user123',
  username: 'travel.junkie',
  fullName: 'Alex Doe',
  profilePictureUrl: 'https://picsum.photos/seed/user123/150/150',
  followers: 125000,
  following: 500,
  postCount: 789,
  engagementRate: 2.5,
  avgLikes: 3125,
  avgComments: 150,
  postingFrequency: "1 post every 2 days",
  recentPosts: [
    {
      id: 'post1',
      platform: 'instagram',
      caption: 'Golden hour in Santorini. Unforgettable! Featuring my friend @photo.fiend',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post1',
      publishedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 4500, comments: 230 },
      thumbnailUrl: 'https://picsum.photos/seed/post1/480/480',
      mediaType: 'IMAGE',
    },
    {
      id: 'post2',
      platform: 'instagram',
      caption: 'Exploring the vibrant streets of Tokyo with @tokyo.explorer.',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post2',
      publishedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 3800, comments: 190 },
      thumbnailUrl: 'https://picsum.photos/seed/post2/480/480',
      mediaType: 'IMAGE',
    },
    {
      id: 'post3',
      platform: 'instagram',
      caption: 'A quick reel of my trip to the Amazon! Big thanks to @rainforest.guides for the tour.',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post3',
      publishedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 6200, comments: 450 },
      thumbnailUrl: 'https://picsum.photos/seed/post3/480/480',
      mediaType: 'VIDEO',
    },
    {
      id: 'post4',
      platform: 'instagram',
      caption: 'What to pack for a weekend getaway. #traveltips Thanks @everyday.carry for the gear!',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post4',
      publishedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 2900, comments: 120 },
      thumbnailUrl: 'https://picsum.photos/seed/post4/480/480',
      mediaType: 'CAROUSEL_ALBUM',
    },
     {
      id: 'post5',
      platform: 'instagram',
      caption: 'Lost in the grand bazaar of Istanbul. @photo.fiend took this shot!',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post5',
      publishedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 4100, comments: 210 },
      thumbnailUrl: 'https://picsum.photos/seed/post5/480/480',
      mediaType: 'IMAGE',
    },
     {
      id: 'post6',
      platform: 'instagram',
      caption: 'Sunrise over the Sahara desert. An amazing experience organized by @desert.adventures.',
      author: 'travel.junkie',
      url: 'https://instagram.com/p/post6',
      publishedAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      metrics: { likes: 5300, comments: 300 },
      thumbnailUrl: 'https://picsum.photos/seed/post6/480/480',
      mediaType: 'IMAGE',
    }
  ],
  followerHistory: [
    { date: 'Jan', value: 110000 },
    { date: 'Feb', value: 112000 },
    { date: 'Mar', value: 115000 },
    { date: 'Apr', value: 118000 },
    { date: 'May', value: 122000 },
    { date: 'Jun', value: 125000 },
  ],
  engagementHistory: [
    { date: 'Jan', value: 2.8 },
    { date: 'Feb', value: 2.6 },
    { date: 'Mar', value: 2.9 },
    { date: 'Apr', value: 2.7 },
    { date: 'May', value: 2.4 },
    { date: 'Jun', value: 2.5 },
  ],
  topMentions: [], // Will be populated by the flow
};
