import { subHours, subDays } from "date-fns";
import type { Post } from "./types";

const now = new Date();

export const demoPosts: Post[] = [
  {
    id: "yt1",
    platform: "youtube",
    title: "I Built a Minecraft House with ONLY DIRT",
    author: "MCBuilderPro",
    url: "#",
    publishedAt: subHours(now, 2).toISOString(),
    engagement: { likes: 12500, comments: 1800, views: 250000 },
    momentum: {
      likes_per_hour: 6250,
      comments_per_hour: 900,
      creator_size_normalized_factor: 1.2,
      age_penalty: 0.5,
      score: 98.5,
    },
    momentumBucket: "On Fire",
    hook: "Think you can't make an epic base with just dirt? Think again. This will blow your mind.",
    patternTags: ["POV", "tutorial"],
    engagementSnapshots: [100, 500, 2000, 5000, 12500],
  },
  {
    id: "rd1",
    platform: "reddit",
    title: "What's a 'once in a lifetime' experience you've had?",
    author: "r/AskReddit",
    url: "#",
    publishedAt: subHours(now, 5).toISOString(),
    engagement: { likes: 25000, comments: 4200 },
    momentum: {
      likes_per_hour: 5000,
      comments_per_hour: 840,
      creator_size_normalized_factor: 0.8,
      age_penalty: 1.2,
      score: 95.1,
    },
    momentumBucket: "On Fire",
    hook: "People are sharing their most incredible 'once in a lifetime' moments, and the stories are wild.",
    patternTags: ["storytime", "listicle"],
    engagementSnapshots: [200, 1000, 5000, 15000, 25000],
  },
  {
    id: "yt2",
    platform: "youtube",
    title: "10-Minute Abs Workout That Actually Works",
    author: "FitLife",
    url: "#",
    publishedAt: subHours(now, 8).toISOString(),
    engagement: { likes: 8200, comments: 750, views: 150000 },
    momentum: {
      likes_per_hour: 1025,
      comments_per_hour: 93.75,
      creator_size_normalized_factor: 1.5,
      age_penalty: 2.0,
      score: 85.3,
    },
    momentumBucket: "Heating",
    hook: "No time for the gym? This 10-minute ab routine will give you the results you want, fast.",
    patternTags: ["tutorial", "countdown", "fitness tips"],
    engagementSnapshots: [50, 200, 1000, 4000, 8200],
  },
  {
    id: "rd2",
    platform: "reddit",
    title: "Entrepreneurs of Reddit, what's your biggest failure and what did you learn?",
    author: "r/Entrepreneur",
    url: "#",
    publishedAt: subHours(now, 12).toISOString(),
    engagement: { likes: 5600, comments: 1100 },
    momentum: {
      likes_per_hour: 466,
      comments_per_hour: 91,
      creator_size_normalized_factor: 1.1,
      age_penalty: 3.5,
      score: 81.0,
    },
    momentumBucket: "Heating",
    hook: "Founders get real about their biggest business flops and the lessons they learned the hard way.",
    patternTags: ["storytime", "listicle"],
    engagementSnapshots: [100, 500, 1500, 3000, 5600],
  },
  {
    id: "yt3",
    platform: "youtube",
    title: "The Ultimate Productivity Hack You've Never Heard Of",
    author: "ProductivityMaster",
    url: "#",
    publishedAt: subHours(now, 22).toISOString(),
    engagement: { likes: 3100, comments: 400, views: 80000 },
    momentum: {
      likes_per_hour: 140,
      comments_per_hour: 18,
      creator_size_normalized_factor: 1.8,
      age_penalty: 5.1,
      score: 75.7,
    },
    momentumBucket: "Heating",
    hook: "Stop using the same old productivity tricks. This one weird method will change how you work.",
    patternTags: ["tutorial", "productivity hacks"],
    engagementSnapshots: [30, 150, 700, 1800, 3100],
  },
  {
    id: "rd3",
    platform: "reddit",
    title: "This AI-generated meme is getting too real",
    author: "r/memes",
    url: "#",
    publishedAt: subHours(now, 1).toISOString(),
    engagement: { likes: 2200, comments: 150 },
    momentum: {
      likes_per_hour: 2200,
      comments_per_hour: 150,
      creator_size_normalized_factor: 0.9,
      age_penalty: 0.2,
      score: 68.2,
    },
    momentumBucket: "Emerging",
    hook: "An AI created a meme about its own existence and now everyone is losing their minds.",
    patternTags: ["meme", "reaction"],
    engagementSnapshots: [50, 400, 900, 1500, 2200],
  },
  {
    id: "yt4",
    platform: "youtube",
    title: "Reacting to the CRAZIEST Minecraft speedruns",
    author: "GamerReacts",
    url: "#",
    publishedAt: subHours(now, 4).toISOString(),
    engagement: { likes: 4500, comments: 600, views: 95000 },
    momentum: {
      likes_per_hour: 1125,
      comments_per_hour: 150,
      creator_size_normalized_factor: 1.0,
      age_penalty: 1.0,
      score: 65.5,
    },
    momentumBucket: "Emerging",
    hook: "These Minecraft speedrunners are on another level. My jaw is on the floor right now.",
    patternTags: ["reaction", "gaming"],
    engagementSnapshots: [100, 800, 2000, 3500, 4500],
  },
  {
    id: "rd4",
    platform: "reddit",
    title: "My POV of the northern lights from my backyard",
    author: "r/pics",
    url: "#",
    publishedAt: subHours(now, 6).toISOString(),
    engagement: { likes: 11000, comments: 300 },
    momentum: {
      likes_per_hour: 1833,
      comments_per_hour: 50,
      creator_size_normalized_factor: 1.3,
      age_penalty: 1.8,
      score: 62.1,
    },
    momentumBucket: "Emerging",
    hook: "You don't need to go to Iceland to see the aurora. This was the view from my house last night.",
    patternTags: ["POV", "storytime"],
    engagementSnapshots: [200, 1000, 3000, 7000, 11000],
  },
    {
    id: "yt5",
    platform: "youtube",
    title: "Green Screen Challenge: TikTok Edition",
    author: "ViralVibes",
    url: "#",
    publishedAt: subDays(now, 1).toISOString(),
    engagement: { likes: 15000, comments: 1200, views: 400000 },
    momentum: {
      likes_per_hour: 625,
      comments_per_hour: 50,
      creator_size_normalized_factor: 0.9,
      age_penalty: 6.0,
      score: 59.8,
    },
    momentumBucket: "Emerging",
    hook: "We tried the viral green screen TikTok challenge, and the results were... interesting. You have to see this.",
    patternTags: ["green-screen", "reaction", "meme"],
    engagementSnapshots: [500, 2000, 6000, 10000, 15000],
  },
  {
    id: "rd5",
    platform: "reddit",
    title: "A simple trick to make your coffee 10x better",
    author: "r/LifeProTips",
    url: "#",
    publishedAt: subHours(now, 18).toISOString(),
    engagement: { likes: 7800, comments: 950 },
    momentum: {
      likes_per_hour: 433,
      comments_per_hour: 52,
      creator_size_normalized_factor: 1.0,
      age_penalty: 4.8,
      score: 58.2,
    },
    momentumBucket: "Emerging",
    hook: "You're probably making your coffee wrong. This one small change makes a huge difference.",
    patternTags: ["tutorial", "listicle"],
    engagementSnapshots: [200, 1000, 2500, 5000, 7800],
  },
];
